export const colors = { gray: "#BCBCBD", green: "#5eead4", purple: "#e879f9", yellow: "#facc15" };
export const scatterplotFakeData = [
  {
    icon: "clear-day",
    moonPhase: 0.48,
    dewPoint: -1.67,
    humidity: 0.54,
  },
  {
    icon: "clear-day",
    moonPhase: 0.52,
    dewPoint: 5.51,
    humidity: 0.57,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.56,
    dewPoint: 6.03,
    humidity: 0.52,
  },
  {
    icon: "fog",
    moonPhase: 0.6,
    dewPoint: 16.64,
    humidity: 0.75,
  },
  {
    icon: "clear-day",
    moonPhase: 0.63,
    dewPoint: -1.71,
    humidity: 0.52,
  },
  {
    icon: "clear-day",
    moonPhase: 0.67,
    dewPoint: -7.22,
    humidity: 0.46,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.71,
    dewPoint: -2.8,
    humidity: 0.53,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.74,
    dewPoint: 13.32,
    humidity: 0.63,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.77,
    precipProbability: 0.32,
    dewPoint: 23.75,
    humidity: 0.65,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.8,
    precipProbability: 0,
    dewPoint: 23.64,
    humidity: 0.7,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.84,
    precipProbability: 0,
    dewPoint: 36.64,
    humidity: 0.83,
  },
  {
    icon: "rain",
    moonPhase: 0.87,
    precipProbability: 1,
    dewPoint: 52.58,
    humidity: 0.95,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.9,
    precipProbability: 0.98,
    dewPoint: 28.24,
    humidity: 0.73,
  },
  {
    icon: "clear-day",
    moonPhase: 0.93,
    precipProbability: 0,
    dewPoint: 2.32,
    humidity: 0.5,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.96,
    precipProbability: 0,
    dewPoint: 12.56,
    humidity: 0.66,
  },
  {
    icon: "cloudy",
    moonPhase: 0.99,
    precipProbability: 0,
    dewPoint: 23.91,
    humidity: 0.79,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.02,
    precipProbability: 0.7,
    precipType: "snow",
    dewPoint: 27.06,
    humidity: 0.85,
  },
  {
    icon: "clear-day",
    moonPhase: 0.05,
    precipProbability: 0,
    dewPoint: 12.32,
    humidity: 0.61,
  },
  {
    icon: "clear-day",
    moonPhase: 0.08,
    precipProbability: 0,
    dewPoint: 17.32,
    humidity: 0.61,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.11,
    dewPoint: 26.35,
    humidity: 0.54,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.14,
    dewPoint: 31.15,
    humidity: 0.66,
  },
  {
    icon: "fog",
    moonPhase: 0.18,
    dewPoint: 38.16,
    humidity: 0.84,
  },
  {
    icon: "rain",
    moonPhase: 0.21,
    dewPoint: 42.45,
    humidity: 0.83,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.25,
    dewPoint: 24.26,
    humidity: 0.58,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.28,
    dewPoint: 8.11,
    humidity: 0.45,
  },
  {
    icon: "clear-day",
    moonPhase: 0.32,
    dewPoint: 12.81,
    humidity: 0.49,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.36,
    dewPoint: 31.88,
    humidity: 0.69,
  },
  {
    icon: "rain",
    moonPhase: 0.4,
    dewPoint: 42.83,
    humidity: 0.84,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.43,
    dewPoint: 30.03,
    humidity: 0.66,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.47,
    dewPoint: 23.96,
    humidity: 0.75,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.51,
    dewPoint: 10.21,
    humidity: 0.52,
  },
  {
    icon: "rain",
    moonPhase: 0.55,
    dewPoint: 26.37,
    humidity: 0.65,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.58,
    dewPoint: 14.67,
    humidity: 0.6,
  },
  {
    icon: "cloudy",
    moonPhase: 0.62,
    dewPoint: 7.22,
    humidity: 0.5,
  },
  {
    icon: "rain",
    moonPhase: 0.65,
    dewPoint: 26.49,
    humidity: 0.71,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.69,
    dewPoint: 21.07,
    humidity: 0.66,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.72,
    dewPoint: 18.3,
    humidity: 0.63,
  },
  {
    icon: "rain",
    moonPhase: 0.75,
    dewPoint: 27.87,
    humidity: 0.83,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.78,
    dewPoint: 17.11,
    humidity: 0.61,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.81,
    dewPoint: 19.57,
    humidity: 0.67,
  },
  {
    icon: "rain",
    moonPhase: 0.84,
    dewPoint: 37.17,
    humidity: 0.88,
  },
  {
    icon: "rain",
    moonPhase: 0.87,
    dewPoint: 45.78,
    humidity: 0.95,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.9,
    dewPoint: 32.11,
    humidity: 0.65,
  },
  {
    icon: "cloudy",
    moonPhase: 0.93,
    dewPoint: 16.71,
    humidity: 0.56,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.96,
    dewPoint: 33.04,
    humidity: 0.72,
  },
  {
    icon: "rain",
    moonPhase: 0.99,
    dewPoint: 46.35,
    humidity: 0.88,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.03,
    dewPoint: 44.46,
    humidity: 0.81,
  },
  {
    icon: "fog",
    moonPhase: 0.06,
    dewPoint: 22.42,
    humidity: 0.66,
  },
  {
    icon: "rain",
    moonPhase: 0.09,
    dewPoint: 27.86,
    humidity: 0.71,
  },
  {
    icon: "fog",
    moonPhase: 0.12,
    dewPoint: 34.89,
    humidity: 0.82,
  },
  {
    icon: "fog",
    moonPhase: 0.16,
    dewPoint: 49.85,
    humidity: 0.86,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.2,
    dewPoint: 56.42,
    humidity: 0.78,
  },
  {
    icon: "rain",
    moonPhase: 0.23,
    dewPoint: 36.88,
    humidity: 0.77,
  },
  {
    icon: "rain",
    moonPhase: 0.27,
    dewPoint: 34.96,
    humidity: 0.9,
  },
  {
    icon: "rain",
    moonPhase: 0.31,
    dewPoint: 41.87,
    humidity: 0.86,
  },
  {
    icon: "rain",
    moonPhase: 0.34,
    dewPoint: 40.02,
    humidity: 0.92,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.38,
    dewPoint: 34.29,
    humidity: 0.69,
  },
  {
    icon: "clear-day",
    moonPhase: 0.42,
    dewPoint: 26.21,
    humidity: 0.49,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.46,
    dewPoint: 33.07,
    humidity: 0.56,
  },
  {
    icon: "rain",
    moonPhase: 0.49,
    dewPoint: 40.76,
    humidity: 0.68,
  },
  {
    icon: "sleet",
    moonPhase: 0.53,
    dewPoint: 34.73,
    humidity: 0.9,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.56,
    dewPoint: 30.03,
    humidity: 0.67,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.6,
    dewPoint: 26.48,
    humidity: 0.6,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.63,
    dewPoint: 24.38,
    humidity: 0.61,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.66,
    dewPoint: 26.96,
    humidity: 0.65,
  },
  {
    icon: "snow",
    moonPhase: 0.7,
    dewPoint: 31.87,
    humidity: 0.91,
  },
  {
    icon: "rain",
    moonPhase: 0.73,
    dewPoint: 28.35,
    humidity: 0.75,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.76,
    dewPoint: 23.85,
    humidity: 0.64,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.79,
    dewPoint: 21.46,
    humidity: 0.57,
  },
  {
    icon: "clear-day",
    moonPhase: 0.82,
    dewPoint: 21.81,
    humidity: 0.54,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.85,
    dewPoint: 26.54,
    humidity: 0.67,
  },
  {
    icon: "snow",
    moonPhase: 0.88,
    dewPoint: 28.86,
    humidity: 0.79,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.91,
    dewPoint: 23.21,
    humidity: 0.63,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.94,
    dewPoint: 22.87,
    humidity: 0.56,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.97,
    dewPoint: 20.46,
    humidity: 0.56,
  },
  {
    icon: "clear-day",
    moonPhase: 0.01,
    dewPoint: 15.18,
    humidity: 0.43,
  },
  {
    icon: "clear-day",
    moonPhase: 0.04,
    dewPoint: 10.85,
    humidity: 0.37,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.07,
    dewPoint: 15.38,
    humidity: 0.44,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.11,
    dewPoint: 14.63,
    humidity: 0.45,
  },
  {
    icon: "fog",
    moonPhase: 0.14,
    dewPoint: 25.72,
    humidity: 0.75,
  },
  {
    icon: "rain",
    moonPhase: 0.18,
    dewPoint: 27.51,
    humidity: 0.65,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.22,
    dewPoint: 23.81,
    humidity: 0.51,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.25,
    dewPoint: 21.14,
    humidity: 0.45,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.29,
    dewPoint: 24.42,
    humidity: 0.58,
  },
  {
    icon: "clear-day",
    moonPhase: 0.33,
    dewPoint: 22.64,
    humidity: 0.54,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.37,
    dewPoint: 24.56,
    humidity: 0.61,
  },
  {
    icon: "cloudy",
    moonPhase: 0.4,
    dewPoint: 37.85,
    humidity: 0.8,
  },
  {
    icon: "fog",
    moonPhase: 0.44,
    dewPoint: 45.02,
    humidity: 0.89,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.47,
    dewPoint: 45.1,
    humidity: 0.83,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.52,
    dewPoint: 24.37,
    humidity: 0.43,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.55,
    dewPoint: 31.58,
    humidity: 0.51,
  },
  {
    icon: "rain",
    moonPhase: 0.58,
    dewPoint: 29.03,
    humidity: 0.73,
  },
  {
    icon: "rain",
    moonPhase: 0.61,
    dewPoint: 34.88,
    humidity: 0.89,
  },
  {
    icon: "rain",
    moonPhase: 0.64,
    dewPoint: 36.93,
    humidity: 0.76,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.67,
    dewPoint: 16.61,
    humidity: 0.41,
  },
  {
    icon: "rain",
    moonPhase: 0.7,
    dewPoint: 31.12,
    humidity: 0.61,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.73,
    dewPoint: 23.76,
    humidity: 0.48,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.76,
    dewPoint: 16.98,
    humidity: 0.44,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.79,
    dewPoint: 19.78,
    humidity: 0.48,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.82,
    dewPoint: 29.49,
    humidity: 0.64,
  },
  {
    icon: "partly-cloudy-night",
    moonPhase: 0.85,
    dewPoint: 25.42,
    humidity: 0.54,
  },
  {
    icon: "partly-cloudy-day",
    moonPhase: 0.88,
    dewPoint: 37.22,
    humidity: 0.61,
  },
];
